/**
 * Emit cross-implementation test vectors for docs/PROTOCOL.md.
 *
 *   node scripts/vectors.js         -> writes spec/vectors.json
 *
 * A second implementation (the Android client first) asserts against this file
 * to prove it derives the same commitments, six-digit codes and session keys as
 * the reference. That turns an encoding mistake into a failing unit test in
 * milliseconds, instead of a pairing that mysteriously never matches on a phone.
 *
 * Every key here is built from a fixed seed, so the output is byte-identical on
 * every run and a diff means the protocol changed.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { computeSasCode, pairingCommitment } from '../src/core/pairing.js';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'spec', 'vectors.json');

// PKCS#8 wrapper for a raw X25519 private key: fixed 16-byte prefix, 32-byte key.
const PKCS8_X25519_PREFIX = Buffer.from('302e020100300506032b656e04220420', 'hex');

/** A deterministic X25519 key pair, so the vectors never move on their own. */
function keyFromSeed(label) {
  const seed = crypto.createHash('sha256').update(`flyshare-vector-${label}`).digest();
  const privateKey = crypto.createPrivateKey({
    key: Buffer.concat([PKCS8_X25519_PREFIX, seed]),
    format: 'der',
    type: 'pkcs8',
  });
  const publicKey = crypto.createPublicKey(privateKey);
  return { privateKey, publicKey, pub: publicKey.export({ format: 'jwk' }).x };
}

function nonceFromSeed(label) {
  return crypto.createHash('sha256').update(`flyshare-nonce-${label}`).digest()
    .subarray(0, 16).toString('base64url');
}

const dh = (mine, theirs) => crypto.diffieHellman({
  privateKey: mine.privateKey,
  publicKey: theirs.publicKey,
});

function sessionKey({ ownEphemeral, peerEphemeral, ownIdentity, peerIdentity, selfId, peerId }) {
  const ephemeralShared = dh(ownEphemeral, peerEphemeral);
  const pairingSecret = dh(ownIdentity, peerIdentity);
  const ordered = [selfId, peerId].sort().join('|');
  const info = Buffer.from(`flyshare-session-v2|${ordered}`, 'utf8');
  return Buffer.from(crypto.hkdfSync('sha256', ephemeralShared, pairingSecret, info, 32));
}

const identityA = keyFromSeed('identity-a');
const identityB = keyFromSeed('identity-b');
const ephemeralA = keyFromSeed('ephemeral-a');
const ephemeralB = keyFromSeed('ephemeral-b');
const nonceA = nonceFromSeed('a');
const nonceB = nonceFromSeed('b');

const idA = 'aaaa1111aaaa1111';
const idB = 'bbbb2222bbbb2222';

const keyOnA = sessionKey({
  ownEphemeral: ephemeralA, peerEphemeral: ephemeralB,
  ownIdentity: identityA, peerIdentity: identityB,
  selfId: idA, peerId: idB,
});
const keyOnB = sessionKey({
  ownEphemeral: ephemeralB, peerEphemeral: ephemeralA,
  ownIdentity: identityB, peerIdentity: identityA,
  selfId: idB, peerId: idA,
});
if (!keyOnA.equals(keyOnB)) throw new Error('session key disagrees between the two ends');

const vectors = {
  note: 'Generated by scripts/vectors.js. Encodings follow docs/PROTOCOL.md; '
    + 'every value is base64url unless stated otherwise.',
  protocolVersion: 2,

  keys: {
    identityA: { private: identityA.privateKey.export({ format: 'jwk' }).d, public: identityA.pub },
    identityB: { private: identityB.privateKey.export({ format: 'jwk' }).d, public: identityB.pub },
    ephemeralA: { private: ephemeralA.privateKey.export({ format: 'jwk' }).d, public: ephemeralA.pub },
    ephemeralB: { private: ephemeralB.privateKey.export({ format: 'jwk' }).d, public: ephemeralB.pub },
  },

  x25519: {
    note: 'Raw shared secrets, to isolate a broken X25519 from a broken KDF.',
    identityAxB: dh(identityA, identityB).toString('base64url'),
    ephemeralAxB: dh(ephemeralA, ephemeralB).toString('base64url'),
  },

  commitment: {
    note: 'PROTOCOL.md §7.2 — the public key is hashed as its base64url TEXT, '
      + 'the nonce as its DECODED bytes.',
    publicKey: identityB.pub,
    nonce: nonceB,
    expected: pairingCommitment(identityB.pub, nonceB),
  },

  sas: {
    note: 'PROTOCOL.md §7.3 — initiator first, never sorted.',
    initiatorPublic: identityA.pub,
    responderPublic: identityB.pub,
    initiatorNonce: nonceA,
    responderNonce: nonceB,
    expected: computeSasCode({
      initiatorPublic: identityA.pub,
      responderPublic: identityB.pub,
      initiatorNonce: nonceA,
      responderNonce: nonceB,
      shared: dh(identityA, identityB),
    }),
  },

  session: {
    note: 'PROTOCOL.md §8.2 — device ids sorted, then joined with "|".',
    deviceIdA: idA,
    deviceIdB: idB,
    expectedPsk: keyOnA.toString('base64url'),
  },

  framing: {
    note: 'PROTOCOL.md §5 — u32 big-endian length, then UTF-8 JSON. Hex.',
    message: { t: 'session', ver: 2, deviceId: idA, ephPub: ephemeralA.pub },
    encoded: null, // filled below
  },
};

const body = Buffer.from(JSON.stringify(vectors.framing.message), 'utf8');
const head = Buffer.allocUnsafe(4);
head.writeUInt32BE(body.length, 0);
vectors.framing.encoded = Buffer.concat([head, body]).toString('hex');

await fs.mkdir(path.dirname(OUT), { recursive: true });
await fs.writeFile(OUT, `${JSON.stringify(vectors, null, 2)}\n`);

console.log(`wrote ${path.relative(ROOT, OUT)}`);
console.log(`  commitment  ${vectors.commitment.expected}`);
console.log(`  sas code    ${vectors.sas.expected}`);
console.log(`  session psk ${vectors.session.expectedPsk}`);
